export const BOOK_LIST_REQUEST = 'BOOK_LIST_REQUEST';
export const BOOK_LIST_SUCCESS = 'BOOK_LIST_SUCCESS';
export const BOOK_LIST_FAIL = 'BOOK_LIST_FAIL';

export const BOOK_BORROW_REQUEST = 'BOOK_BORROW_REQUEST';
export const BOOK_BORROW_SUCCESS = 'BOOK_BORROW_SUCCESS';
export const BOOK_BORROW_FAIL = 'BOOK_BORROW_FAIL';

export const BOOK_BORROW_COPY_REQUEST = 'BOOK_BORROW_COPY_REQUEST';
export const BOOK_BORROW_COPY_SUCCESS = 'BOOK_BORROW_COPY_SUCCESS';
export const BOOK_BORROW_COPY_FAIL = 'BOOK_BORROW_COPY_FAIL';
