export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_ADD_ITEM_COPY = 'CART_ADD_ITEM_COPY';

export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_REMOVE_ITEM_COPY = 'CART_REMOVE_ITEM_COPY';
